services:
  gateway:
    image: ${REGISTRY}/eisot-xml-gateway:${IMAGE_TAG}
    restart: always
    volumes:
      - /etc/letsencrypt:/etc/letsencrypt:ro
      - /var/www/html:/var/www/html:ro
    ports:
      - "80:80"
      - "443:443"
    depends_on:
      - frontend-node
      - api

  frontend-node:
    image: ${REGISTRY}/eisot-xml-frontend-node:${IMAGE_TAG}
    restart: always
    environment:
      - NODE_ENV=production
      - NEXT_PUBLIC_BACKEND_URL=https://api.${API_SITE_NAME}
      - INTERNAL_BACKEND_URL=http://api
      - PORT=3000
      - GRANT_TYPE=${GRANT_TYPE}
      - CLIENT_ID=${CLIENT_ID}
      - CLIENT_SECRET=${CLIENT_SECRET}
    expose:
      - "3000"
    depends_on:
      - api

  api:
    image: ${REGISTRY}/eisot-xml-api:${IMAGE_TAG}
    restart: always
    depends_on:
      - api-php-fpm

  api-php-fpm:
    image: ${REGISTRY}/eisot-xml-api-php-fpm:${IMAGE_TAG}
    restart: always
    environment:
      APP_DEBUG: 0
      APP_ENV: prod
      SITE_URL: ${API_SITE_URL}
      SITE_NAME: ${API_SITE_NAME}
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app
      MAILER_DSN: ${API_MAILER_DSN}
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: admin
      FRONTEND_URL: ${API_SITE_URL}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/%2f/messages
      SENTRY_DSN: ${SENTRY_DSN}
      JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    depends_on:
      api-postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy
    secrets:
      - jwt_public_key
      - jwt_private_key

  api-php-cli:
    image: ${REGISTRY}/eisot-xml-api-php-cli:${IMAGE_TAG}
    environment:
      APP_DEBUG: 0
      APP_ENV: prod
      SITE_URL: ${API_SITE_URL}
      SITE_NAME: ${API_SITE_NAME}
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app
      MAILER_DSN: ${API_MAILER_DSN}
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: admin
      FRONTEND_URL: ${API_SITE_URL}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/%2f/messages
      SENTRY_DSN: ${SENTRY_DSN}
      JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    depends_on:
      api-postgres:
          condition: service_started
      rabbitmq:
        condition: service_healthy
    secrets:
      - jwt_public_key
      - jwt_private_key

  api-postgres:
    image: postgres:12.2-alpine
    restart: always
    environment:
      POSTGRES_USER: app
      POSTGRES_PASSWORD: ${API_DB_PASSWORD}
      POSTGRES_DB: app
    ports:
      - "127.0.0.1:5432:5432"
    volumes:
      - api-postgres:/var/lib/postgresql/data

  rabbitmq:
    image: rabbitmq:3.13-management-alpine
    ports:
      - "127.0.0.1:15672:15672"
    environment:
      RABBITMQ_DEFAULT_USER: ${RABBITMQ_USER}
      RABBITMQ_DEFAULT_PASS: ${RABBITMQ_PASSWORD}
    volumes:
      - rabbitmq_data:/var/lib/rabbitmq
    restart: always
    healthcheck:
      test: rabbitmq-diagnostics -q ping
      interval: 10s
      timeout: 5s
      retries: 5
      start_period: 20s

  api-php-worker:
    image: ${REGISTRY}/eisot-xml-api-php-cli:${IMAGE_TAG}
    environment:
      APP_DEBUG: 0
      APP_ENV: prod
      SITE_URL: ${API_SITE_URL}
      SITE_NAME: ${API_SITE_NAME}
      DB_HOST: api-postgres
      DB_USER: app
      DB_PASSWORD: ${API_DB_PASSWORD}
      DB_NAME: app
      MAILER_DSN: ${API_MAILER_DSN}
      MAILER_FROM_EMAIL: ${API_MAILER_FROM_EMAIL}
      MAILER_FROM_NAME: admin
      FRONTEND_URL: ${API_SITE_URL}
      YOOKASSA_SHOP_ID: ${YOOKASSA_SHOP_ID}
      YOOKASSA_SECRET_KEY: ${YOOKASSA_SECRET_KEY}
      MESSENGER_TRANSPORT_DSN: amqp://${RABBITMQ_USER}:${RABBITMQ_PASSWORD}@rabbitmq:5672/%2f/messages
      SENTRY_DSN: ${SENTRY_DSN}
      JWT_ENCRYPTION_KEY: ${JWT_ENCRYPTION_KEY}
      JWT_PUBLIC_KEY_PATH: /run/secrets/jwt_public_key
      JWT_PRIVATE_KEY_PATH: /run/secrets/jwt_private_key
    secrets:
      - jwt_public_key
      - jwt_private_key
    command: php bin/console messenger:consume async --limit=1000 --memory-limit=128M --no-debug -vv
    stop_grace_period: 30s
    restart: always
    depends_on:
      api-postgres:
        condition: service_started
      rabbitmq:
        condition: service_healthy

volumes:
  api-postgres:
  rabbitmq_data:

secrets:
  jwt_public_key:
    file: ./secrets/jwt_public.key
  jwt_private_key:
    file: ./secrets/jwt_private.key